### ISSUE TITLE
Remove core doc

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa-docs#1]
My opinion is to remove doc that is mostly targeting core developer from docs.massa.net that mostly target users. I would remove:
https://docs.massa.net/en/latest/technical-doc/vm-ledger-interaction.html
https://docs.massa.net/en/latest/technical-doc/concurrency.html
WDYT ?

In that case where do you want to put it.

cc @damip @gregLibert

**Comment by damip** [comment]
Those two documents are not up to date anyways, I vote for deleting them for now

**Comment by gregLibert** [comment]
> Those two documents are not up to date anyways, I vote for deleting them for now

+1

**Comment by qdrn** [comment]
Done. Closing.
