### ISSUE TITLE
How to get massa on innonet ?

### ISSUE THREAD

**Issue by lilyanB** [massalabs/massa-docs#109]
How to have Massa in inno net?
I created a wallet here : https://massa.net/testnet/wallet
I'm connected with this RPC : https://inno.massa.net/test18

what is the process to get Massa?
Thanks

**Comment by leoloco** [comment]
To add a little more context, when developing smart contracts on the innonet, what is the process to obtain Massa tokens ? It seems that the current process to fund a wallet on innonet is "ask someone from the inno team". It is obviously a sub-optimal process that won't scale. So the question is, what is the optimal way to develop on innonet ? Is there an automatic process to get tokens on the innonet ? Or should we set up a local sandbox ?

**Comment by qdrn** [comment]
cc @massalabs/innovation

**Comment by SlnPons** [comment]
Thanks for creating an issue and stating your need. We'll study your request and come back to you shortly! 
I'm joking ;)
So far we had only one partner using our Innonet (Dusa) and they didn't have this need frequently so you are right we were and still are managing this manually :/
 ut now we have more and more people using Innonet, we need to address it asap. I'll send you a workaround that we're using within the Inno team on private DM to unblock you in the meantime. And I'll come back with possible solutions to get your opinion on them vert soon. Thanks guys :)
