### ISSUE TITLE
Improve Autonomous SC section in Docs

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/massa-docs#114]
**The context:**
@peterjah [updated](https://github.com/massalabs/massa-sc-examples/issues/48) the example on ASC triggers last week. 
Our ASC documentation currently has this content:

- Intro: description of sendMessage ABI and available set of conditions
- Link to the ticker example (sourcecode)
- Different ways to execute smart contracts 

**The need:**
Using Massa-in-action (MiA) product, create the first interactive documentation example for ASC (trigger contract), so that developers can see the code and it's explanation (usage, reasons, limitations if any), directly in an interactive documentation.

Additional step would be mocking function's execution in the MiA interface.

**How-to:**
- Massa-in-action can be deployed on a server (same as we do for SC-Playground), and a link to it provided in the ASC section. 
- Code is pretty good, check here: https://github.com/massalabs/hackathons/tree/main/massa-in-action.

**Technical details:**

**Comment by longgamma-massa** [comment]
@gregLibert

**Comment by Ben-Rey** [comment]
The issue will be moved to massa-in-action
