### ISSUE TITLE
Improve and update SC documentation (Massa docs) (2/3)

### ISSUE THREAD

**Issue by Thykof** [massalabs/massa-docs#12]
See related issue: https://github.com/massalabs/massa-docs/issues/7

scope of the issue:
- create a decentralized application with Thyra to interact with our smart contract

Use this paragraph is the introduction:

    For the decentralized website part, we'll assume that you have some familiarity with HTML and JavaScript. If you want to have more details, you can follow `this great tutorial from React <https://reactjs.org/tutorial/tutorial.html>`_ from which the dApp is heavily inspired from.

Task: create a massa web3 subscetion and introduce the libraries (sdk, toolkit, web3...) and introduce the repo https://github.com/massalabs/massa-dapp-example-sum. list the prerequisites: smart contract, thyra

**Comment by qdrn** [comment]
Related #26. When Thyra/decentralized web section is ready we should refer to it in the hackathon's specific doc.

**Comment by qdrn** [comment]
Reopening as, as far as I can see, this hasn't been done (see https://docs.massa.net/en/latest/hackathon.html).

**Comment by qdrn** [comment]
cc @gregLibert @Thykof

**Comment by qdrn** [comment]
Sorry, wrong issue.
