### ISSUE TITLE
Wrong link for massa standards

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/massa-docs#155]
Location: [Useful resources section](https://docs.massa.net/en/latest/web3-dev/useful-resources.html)

Wrong link and names of token types for:
[massa-sc-standards](https://sc-standards.docs.massa.net/) AssemblyScript package containing standards implementation (fongible token, non fongible token) 

Fix to:
link -> [massa-standards](https://github.com/massalabs/massa-standards) 
new description of what massa-standards contains (wallet standard, smart-contract standards, etc)

**Comment by qdrn** [comment]
Do you mind fixing this quickly @windushka ? No need to make something fancy as this doc will soon be outdated.
