### ISSUE TITLE
Types [SC documentation] section update

### ISSUE THREAD

**Issue by longgamma-massa** [massalabs/massa-docs#20]
**The need:**
We must update this outdated section https://docs.massa.net/en/latest/web3-dev/types.html
It can be done after all the sections of the Web3 developers are covered.

**Prerequisties:**
SC documentation update
Decentralized web update

**Comment by qdrn** [comment]
@gregLibert I think we forgot this one. Or did not have time to handle it. What do you want to do with it ?
