### ISSUE TITLE
Add a formatter

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa-docs#24]
It would be nice to add a formatter to avoid big lines, etc...

Maybe @thomas-senechal you can have a look once the work on translation is over ?
cc @SlnPons

**Comment by thomas-senechal** [comment]
I searched for Visual Studio Code formatters extensions, there are multiple extensions for `.rst` files such as [`reStructuredText` by `LeXtudio Inc.`](https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext) which seems to be the most known, those extensions implement linter, the ability to preview the result and other features like that, but no formatter are available.

I think we can simply use [`sphinx-lint`](https://pypi.org/project/sphinx-lint/) as a linter. It doesn't provide a `fix` option to automaticaly fix the formatting errors, but it gives a list of the errors and can be configured to our needs. 
It also provides a `--max-line-length` option to set the max line length to our wish.

**Comment by qdrn** [comment]
> I searched for Visual Studio Code formatters extensions, there are multiple extensions for `.rst` files such as [`reStructuredText` by `LeXtudio Inc.`](https://marketplace.visualstudio.com/items?itemName=lextudio.restructuredtext) which seems to be the most known, those extensions implement linter, the ability to preview the result and other features like that, but no formatter are available.
> 
> I think we can simply use [`sphinx-lint`](https://pypi.org/project/sphinx-lint/) as a linter. It doesn't provide a `fix` option to automaticaly fix the formatting errors, but it gives a list of the errors and can be configured to our needs. It also provides a `--max-line-length` option to set the max line length to our wish.

Thanks. When you have time if you can add it to the CI it would be perfect!
