### ISSUE TITLE
Mention Thyra in hackathon doc

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa-docs#26]

**Comment by SlnPons** [comment]
Using this issue to update this part part of the doc: https://docs.massa.net/en/latest/web3-dev/decentralized-web.html#

**Comment by qdrn** [comment]
Reopening as, as far as I can see, this hasn't been done (see https://docs.massa.net/en/latest/hackathon.html).

cc @longgamma-massa @SlnPons

**Comment by qdrn** [comment]
Closed in #38
