### ISSUE TITLE
Move `Building Decentralized Application` section

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa-docs#58]
I think having this section https://docs.massa.net/en/latest/web3-dev/massa-web3.html#building-decentralized-application in the middle of massa-web3 is confusing. It's pretty specific to massa-web3.

cc @gregLibert @longgamma-massa @SlnPons

**Comment by qdrn** [comment]
For now it's called massa-web3 similarly to the web3 js library in eth (https://web3js.readthedocs.io/en/v1.8.1/) and it refers to the massa-web3 TS library.

I agree that right now it might be unclear.

**Comment by gregLibert** [comment]
So, I propose to :
- explain all this in the introduction of this page
- provide useful links to other web3 topics in the introduction
- remove any misleading topic about Thyra or dApp in this section (except the introduction).
@longgamma-massa @SlnPons wdyt ?

**Comment by qdrn** [comment]
Sounds good to me.

**Comment by SlnPons** [comment]
It makes sense to me too.
Is there any important due date for this doc to be updated (ofc I know the public doc should always reflect the current state and be updated. But just so we can focus our efforts on the right things).

**Comment by SlnPons** [comment]
@longgamma-massa I'm not sure this is a P2 tbh. We don't have any due date so better not use time now to do it. Plus I think this is a PM task, not a dev one. 
What do you think?

**Comment by longgamma-massa** [comment]
> @longgamma-massa I'm not sure this is a P2 tbh. We don't have any due date so better not use time now to do it. Plus I think this is a PM task, not a dev one. What do you think?

yep, defo after last nights clean up is not P2. Aligned.
