### ISSUE TITLE
Update and improve node docs

### ISSUE THREAD

**Issue by damip** [massalabs/massa-docs#6]
* remove stuff specific to old testnets in the node setup page
* add testnet16-specific stuff (eg. bootstrap, including whitelist)
* under the "TODO" on the PoS explanation webpage, explain that those are things that are not there yet but that we expect to include in the future

@aoudiamoncef @AurelienFT  can you have a quick look together ?

**Comment by AurelienFT** [comment]
> * remove stuff specific to old testnets in the node setup page
> * add testnet16-specific stuff (eg. bootstrap, including whitelist)
> * under the "TODO" on the PoS explanation webpage, explain that those are things that are not there yet but that we expect to include in the future
> 
> @aoudiamoncef @AurelienFT can you have a quick look together ?

In testnet16 specific I don't see anything else than bootstrap whitelist that need to be said to the user.
