### ISSUE TITLE
Improve sc getting started

### ISSUE THREAD

**Issue by qdrn** [massalabs/massa-docs#80]
I believe that right now, the way option 1 and 2 of the [getting started section](https://docs.massa.net/en/latest/web3-dev/smart-contracts/getting-started.html#execute-the-smart-contract-on-the-node) are presented is confusing. It makes user believe that the two options does the same thing. That not the case as in option 1 it will deploy a SC that needs to be called while in option 2 it really executes the SC, effectively emitting the event.

I think we should clarify the difference, and also explain how to call the SC in the case of option 1.

**Comment by qdrn** [comment]
cc @Thykof

**Comment by longgamma-massa** [comment]
@Thykof relates to https://github.com/massalabs/massa-sc-toolkit/issues/79

**Comment by qdrn** [comment]
Trying to clarify stuff here: https://github.com/massalabs/massa-docs/tree/getting-started

**Comment by qdrn** [comment]
See related PR: https://github.com/massalabs/massa-docs/pull/81

**Comment by qdrn** [comment]
I think we should only display one option for deployment: less work to maintain doc, easier for users, and that's why we are developing the toolkit...

WDYT ? cc @longgamma-massa @gregLibert @Thykof

**Comment by Thykof** [comment]
originally the idea of the second option was to allow advanced user to fully understand how it work at a low level.

but I agree
